config/defaults.ini
hooks/image/60-kolibri-content

After installing and enabling kolibri_app_desktop_xdg_plugin, Kolibri
will automatically create launchers for channels in a well-known
location.
https://phabricator.endlessm.com/T31664

hooks: Generate Kolibri channel launchers

---

config/defaults.ini
hooks/image/62-kolibri-automatic-provision-install

https://phabricator.endlessm.com/T31679

hooks: Add a hook to generate Kolibri automatic_provision.json

---

config/defaults.ini

https://phabricator.endlessm.com/T31786

config: Do not create a Kolibri admin user

---

config/defaults.ini
helpers/kolibri-pick-content-from-channel
hooks/image/60-kolibri-content
hooks/image/61-kolibri-content-install

https://phabricator.endlessm.com/T31788

hooks: Support installing a subset of a kolibri channel

---

hooks/image/60-kolibri-content

https://phabricator.endlessm.com/T31788

hooks: Convert channel_id to uppercase

---

config/defaults.ini
helpers/create-usb-image
helpers/eos-write-live-image-data-only
stages/eib_image

https://phabricator.endlessm.com/T31962

helpers: Add a way to create a data-only USB image

---

config/defaults.ini

https://phabricator.endlessm.com/T30865

config: Include H.264 and MPEG4 by default

---

config/personality/en.ini

https://phabricator.endlessm.com/T32522

config: add Kolibri content to the en personality

---

config/defaults.ini

Thread: https://community.endlessos.com/t/apps-that-have-flatpaks/17442/4
https://phabricator.endlessm.com/T31431

Move shotwell to flatpak

---

config/personality/pt_BR.ini

This app does not exist on eos-apps.

pt_BR: Drop inexistent app com.endlessm.extra.pt_BR

---

config/personality/pt_BR.ini
data/settings/pt_BR/background

config: pt_BR: Do not use a different desktop background

---

config/branch-personality/master-base.ini
config/branch/master.ini
config/defaults.ini
lib/eibflatpak.py

https://phabricator.endlessm.com/T32629

config: Use Kolibri beta for master branch builds

---

config/defaults.ini

https://phabricator.endlessm.com/T32879

config: Move gedit to flatpak

---

config/defaults.ini

https://phabricator.endlessm.com/T32906

config: Move gnome-calculator to flatpak

---

config/defaults.ini

https://phabricator.endlessm.com/T32908

config: Move gnome-logs to flatpak

---

config/defaults.ini

https://phabricator.endlessm.com/T32912

config: Move gnome-font-viewer to flatpak

---

config/defaults.ini
hooks/image/61-kolibri-content-install

Add more facility and device settings. Use defaults more proper for
the seamless user management case.
https://phabricator.endlessm.com/T32885

Kolibri automatic provisioning: Change default settings

---

config/defaults.ini
hooks/image/61-kolibri-content-install
hooks/image/62-kolibri-automatic-provision

https://phabricator.endlessm.com/T32885

T32885 split automatic provision

---

config/defaults.ini

https://phabricator.endlessm.com/T32983

config: Move gnome-contacts to flatpak

---

config/defaults.ini

https://phabricator.endlessm.com/T33040

config: Move file-roller to flatpak

---

hooks/image/62-kolibri-automatic-provision

https://phabricator.endlessm.com/T33314

Hooks: Update format for Kolibri automatic provisioning

---

config/personality/en.ini
config/personality/es.ini
config/personality/fr.ini
config/personality/pt_BR.ini

This content was added to serve as example Kolibri content, but 
ultimately it was decided that increasing the image size by so much
without a diverse selection of content was not the best way to go about
it.
https://phabricator.endlessm.com/T33357

Revert adding KA to downloadable images

---

.github/workflows/tests.yml
config/arch/arm64.ini
config/branch-arch/master-arm64.ini
hooks/content/50-flatpak
hooks/image/50-flatpak.chroot
lib/applist.py
lib/eibflatpak.py
tests/data/flatpak/app-1-locale/metadata
tests/data/flatpak/app-1/metadata
tests/data/flatpak/app-2-locale/metadata
tests/data/flatpak/app-2/metadata
tests/data/flatpak/app-extra-data/metadata
tests/data/flatpak/platform-1-locale/metadata
tests/data/flatpak/platform-1/metadata
tests/data/flatpak/platform-2-locale/metadata
tests/data/flatpak/platform-2/metadata
tests/eib/test_eibflatpak.py
tests/eib/test_eibostree.py
tests/util.py

The custom Flatpak installation code had become broken for arm64. This changes it to be a bit less bespoke by relying on Flatpak transactions. That all happens in the last commit, which is massive. Apologies. While here a pile of test code was added.
https://phabricator.endlessm.com/T33827

Use Flatpak transactions

---

lib/eibflatpak.py
tests/eib/test_eibflatpak.py

A couple cleanups @wjt spotted in #89 after review.
https://phabricator.endlessm.com/T33827

T33827 followups

---

hooks/image/50-xkb-layout.chroot

This will be used by some custom images.
https://phabricator.endlessm.com/T33987

image: Support XKB keyboard variants

---

config/defaults.ini

* Add eos4.0 config to set eos4.0 branch's stable_branch
* Bump the default stable_branch to latest2
https://phabricator.endlessm.com/T33353

config: Bump the default stable_branch to latest2

---

config/defaults.ini

Doesn't make a difference, but it's good to list it there.

config: Add xkb_variant to defaults.ini

---

config/defaults.ini
hooks/image/50-xkb-layout.chroot

https://phabricator.endlessm.com/T33987

Backport T33987 to eos4.0

---

config/personality/es.ini

https://phabricator.endlessm.com/T35103

config: Add Endless Key collections for es personality

---

config/personality/en.ini

https://phabricator.endlessm.com/T34961

config: Add spanish-extras collection to the es personality

---

config/defaults.ini

https://phabricator.endlessm.com/T32962

Replace gedit with Text Editor

---

config/arch/arm64.ini
config/defaults.ini

https://phabricator.endlessm.com/T35401

Preinstall Arduino IDE v2

---

config/personality/es.ini

Device-access team has revised the content of the generic EOS ES image. Add following apps accordingly:
| Name | App ID |
| --- | --- |
| Agricultura | com.endlessm.farming.es_GT |
| Microempresas | com.endlessm.microenterprises.es_GT |
| Programación | com.endlessm.programming |
| Empresas sociales | com.endlessm.social_enterprises.es_GT |
| Mundo animal | com.endlessm.video_animal_kingdom |
| Vroom | com.endlessm.vroom.es |
| Arduino Projects | com.endlessnetwork.arduinoprojects |
| Blender Tutorials | com.endlessnetwork.blendertutorials |
| CSS Tutorials | com.endlessnetwork.csstutorials |
| HTML Tutorials | com.endlessnetwork.htmltutorials |
| Science Snacks | com.endlessnetwork.sciencesnacks |
| Museum of All Things | as.may.moat |
| Calculus | com.github.carlos157oliveira.Calculus | …

config: ES: Add more apps into generic EOS ES images
