endlessm/eos-image-builder

.github/workflows/tests.yml, README.md, config/defaults.ini, lib/eibflatpak.py, run-build, tests/conftest.py, tests/test_image_builder.py
Stop gathering architecture details during setup with `dpkg-architecture` so that the dpkg-dev package isn't needed on the host. Instead, dpkg-dev is included in the buildroot so that `dpkg-architecture` is available if needed.
https://phabricator.endlessm.com/T31702
=> Remove host dpkg-dev requirement

run-build
Nothing in /etc/eos-image-builder is required to build an image, so it
may not exist on the host. Make mounting it optional.
https://phabricator.endlessm.com/T31702
=> ImageBuildRoot: Make /etc/eos-image-builder mount optional

config/product/eoscustom.ini, lib/eib.py, tests/conftest.py, tests/test_image_builder.py
With the image builder now public, presumably people will want to build
their own images. In order to not confuse these images with official
Endless eos images, add a new default product named eoscustom.
This is nearly the same as an eos image with a few exceptions:
* No ISO or VM images
* No automatic Google Chrome
* No xz compression
These settings could be added, but they can also be customized by users
using the normal methods.
https://phabricator.endlessm.com/T31707
=> Add new default product eoscustom

helpers/split-image, hooks/publish/42-sha256sums, lib/eib.sh, stages/eib_image, tests/test_eib_sh.py
Include the target in the individual checksum files so that they can be passed to `sha256sum --check` like the combined checksum file.
https://phabricator.endlessm.com/T31076
=> Full sha256sum files

data/arm64/boot.src, stages/eib_image
EOS makes OSTree deploy device tree folder for arm64 platforms, instead
of a single FIT-uImage including multiple DTBs. So, U-Boot's boot script
should load the DTB in the corresponding path simply and directly.
https://phabricator.endlessm.com/T31726
=> eib_image: Make U-Boot load corresponding DTB directly

stages/eib_image
In d8e43c39272d39131a560ff2f2be61ca556d77e3 the split image process was
moved after the ISO creation since it destructively edits the raw image.
However, this also moved the `wait` that was blocking on the
uncompressed signature file which the ISO creation needed. This
sometimes causes a race if the signature isn't completed before
`create-iso` is called.
Unfortunately, previously the race would be silently ignored because
`create-iso` assumes that if the signature file didn't exist it was
intentional. However, now it has a hard requirement on the uncompressed
image checksum file, which is also created in the background at the same
time.
This adds back the wait with a slight optimization that it only happens
when creating an ISO.
https://phabricator.endlessm.com/T31304
=> image: Fix race between ISO and checksum creation

config/defaults.ini, config/personality/base.ini, config/personality/es.ini, config/personality/fr.ini
This adds some simple Kolibri content (and automatic provisioning) to the `base` personality.
https://phabricator.endlessm.com/T31866
=> config: Add Kolibri content to the base personality

README.md
It's part of how mmdebstrap-setup/cleanup helpers work.
=> Needs rsync

helpers/split-image
This is the last usage of python2 in the image builder. After this it
can be dropped from the buildroot.
=> split-image: Use python3 for disk size calculations

config/defaults.ini
I was able to build images fine without it and don't see any scripts that need it.
=> Remove python2 from buildroot

config/arch/arm64.ini
This runtime extension is not available for arm64.
https://phabricator.endlessm.com/T30865
=> config: Do not include org.freedesktop.Platform.openh264 for arm64

config/branch/master.ini, config/defaults.ini
The latest eos-apps are available on the eos3 branch of the eos-apps
flatpak repo. We are not develpoing these apps anymore, so it probably
does not make sense to push a eos4 ref to this repo.
https://phabricator.endlessm.com/T32376
=> config: Set eos-apps repo to use eos3 branch by default

config/branch/master.ini, config/defaults.ini
We'd like new images to track the `latestX` ostree branch across major
versions rather than following the major series `eosN` branch. The major
series branches still exist and may be used by LTS products that are
designed to stay on a specific version of EOS.
https://phabricator.endlessm.com/T32596
=> config: Follow latest1 ostree branch by default

data/branding/gnome-initial-setup/default/gnome-initial-setup.conf, data/branding/gnome-initial-setup/es/gnome-initial-setup.conf
This is where we disclose our use of the Mozilla Location Service and
provide its terms of use. We are required to disclose this as a
condition of using the MLS API.
https://phabricator.endlessm.com/T32649
=> Re-enable privacy page in Initial Setup

config/defaults.ini, config/personality/base.ini, config/personality/en.ini, config/personality/es.ini, config/personality/fr.ini, config/personality/pt_BR.ini
Drops outdated "Kolibri on Endless OS" documentation channel and includes localized Khan Academy content and the TED-Ed Kolibri channel.
=> config: Adjust pre-loaded Kolibri content on base, en, es, fr and pt_BR images

config/defaults.ini, config/personality/es.ini, config/personality/fr.ini
We are not installing this channel by default anymore, but having the
section specifying its node ids ends up pulling the channel in anyway.
=> config: Drop the section for the "Kolibri on EOS" channel from default, es, fr, pt_BR

hooks/image/60-kolibri-content
When the hook that downloads Kolibri content runs, its target directory
may already exist and have content from the previous run, which may be
from a different image configuration.
This commit removes any previously exiting content to prevent that
content from being included in the image being built.
https://phabricator.endlessm.com/T32712
=> kolibri: Clear local dir before downloading content

eos-image-builder
The instructions in endless-image-config suggest you can do `/path/to/eos-image-builder --localdir .`, but that doesn't actually work when the working directory is changed in order to call `./run-build`. Once `run-build` is called the `--localdir` path is converted to absolute, but by then it's too late.
=> Handle --localdir relative paths correctly

config/defaults.ini, hooks/image/61-kolibri-content-install, hooks/image/62-kolibri-automatic-provision
These are backports of #49 and #55 to the eos4.0 stable branch. I believe they're all appropriate for stable image builds since Kolibri and the relevant plugins have all been released (@dylanmccall correct me if I'm wrong).
https://phabricator.endlessm.com/T32885
=> Kolibri provisioning eos4.0 backports

README.md, run-build
While lightly used, the config schema can be useful to ensure options constrained to supported values. Currently this is only read from the eib config directory, but it should also be read from a local configuration directory. There it makes more sense as a local config directory is likely targeted to a much narrower scope and can better define what values are supported.
https://phabricator.endlessm.com/T33034
=> Support config schema in local config dir

hooks/image/60-kolibri-content
Since flathub/org.learningequality.Kolibri#40, the Kolibri flatpak
disables symlinks by default.
https://phabricator.endlessm.com/T33170
=> hooks: Remove options.ini file with STATIC_USE_SYMLINKS

helpers/mmdebstrap-cleanup, helpers/mmdebstrap-setup, run-build
The mmdebstrap hooks were doing entirely the wrong thing by syncing
between the image builder's apt cache and the **system's**
`/var/cache/apt/archives`. That's both wrong and pointless.
Changing that to sync into the buildroot's apt archives makes
`mmdebstrap` throw an error. Apparently it uses the contents of
`/var/cache/apt/archives` to figure out what to install after telling
apt to download packages, so it requires the directory to be empty when
it starts.
To bring this back, something like apt-cacher that works at the network
level is needed.
Fixes: #63
This should be backported to the eos4.0 branch.
=> ImageBuildRoot: Disable buildroot apt cache handling

config/defaults.ini, hooks/image/60-kolibri-content
To offload our Learning Equality's CDN, we've setup our own CDN in front
of it at https://kolibri-content.endlessos.org. Import channels using
that as the base URL and configure deployments to use it. The
configuration can be cleared to go back to the default URL.
https://phabricator.endlessm.com/T30950
=> kolibri: Use our content CDN by default

stages/eib_image
Until now we've relied on ostree's automatic bootloader detection, which
relies on the presence of certain files to determine which bootloader is
in use. Instead we should specify what bootloader to use so the decision
is unambiguous.
When grub is the bootloader, we actually don't want to use ostree's grub
integration. That tries to update grub.cfg whereas we just want it to
update the BLS entries since our grub can read those and our grub.cfg
doesn't support updating. This will help us drop an ugly downstream hack
that makes the ostree grub bootloader integration do nothing.
https://phabricator.endlessm.com/T33364
=> image: Specify bootloader to ostree

config/defaults.ini
The newest version of the Kolibri flatpak uses these versions.
https://phabricator.endlessm.com/T33318
=> Update Kolibri module versions

config/defaults.ini, hooks/image/60-kolibri-content
The point of this is to make installing channel contents reliable. However, this is a draft for now since it depends on the not-yet-released 0.15.3.
https://phabricator.endlessm.com/T33363
https://phabricator.endlessm.com/T33365
=> Kolibri importcontent fixes

config/defaults.ini, hooks/image/60-kolibri-content
Backport the kolibri importcontent fixes from master to make it reliable.
https://phabricator.endlessm.com/T33363
https://phabricator.endlessm.com/T33365
=> Kolibri importcontent fixes backports

config/defaults.ini, hooks/image/60-kolibri-content
To offload our Learning Equality's CDN, we've setup our own CDN in front
of it at https://kolibri-content.endlessos.org. Import content using
that as the base URL. Installations are still configured to use the
Kolibri default URL. The configuration can be cleared to go back to the
default URL for builds, too.
https://phabricator.endlessm.com/T30950
https://phabricator.endlessm.com/T33499
This backports #65 to eos4.0.
=> kolibri: Use our content CDN during builds

config/defaults.ini
Our CDN is having some issues with downloading content from Kolibri
Studio, which is causing problems with objects being unavailable. We are
reverting back to downloading directly from Kolibri Studio while those
issues get sorted.
https://phabricator.endlessm.com/T33704
=> config: Temporarily bypass our Kolibri CDN

lib/eibflatpak.py
Example output:
+ 13:25:17 WARNING eibflatpak: app/com.github.lainsce.notejot/x86_64/stable in flathub is marked as EOL: The application has been renamed to Notejot (io.github.lainsce.Notejot)
+ 13:25:17 WARNING eibflatpak: runtime/org.gnome.Platform/x86_64/3.28 in flathub is marked as EOL: The GNOME 3.28 runtime is no longer supported and does not receive security updates. Please ask your application developer to migrate to a supported platform.
+ 13:25:17 WARNING eibflatpak: runtime/org.freedesktop.Platform/x86_64/19.08 in flathub is marked as EOL: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
+ 13:25:17 WARNING eibflatpak: runtime/com.github.lainsce.notejot.Locale/x86_64/stable …
=> Fail build if Flatpaks are marked eol-rebase

config/arch/arm64.ini
The Blender flatpak builds failed on arm64 now. See the ticket "Support
aarch64 architecture". [1] So, drop Blender on arm64 platforms.
[1]: https://github.com/flathub/org.blender.Blender/issues/99
https://phabricator.endlessm.com/T33749
=> config: arm64: Remove Blender which is not available on arm64

helpers/generate-ovf-files
The meat is in the topmost commit: generate-ovf-files: Compress vmdk with pigz
'zip' cannot compress in parallel. 'pigz', which we already use elsewhere in eos-image-builder, can. It has a '--zip' flag to emit a ZIP file.
The rest is cleanup, though the logging change should make it possible to actually check what is taking time during this script.
In last night's master base image build, 00:03:30 - 00:12:56 was create-vm-image, i.e. 9m 26s.
https://phabricator.endlessm.com/T33762
=> Improve OVF generation

stages/eib_image
Increase the ESP size on PAYG systems, which use sd-boot, as 250MB is
becoming too small to hold 3 kernel+initrd images, plus whatever else
needs to live in the ESP, at during an update.
https://phabricator.endlessm.com/T33800
=> IMAGE: Increase ESP size on PAYG / sd-boot systems

config/arch/arm64.ini
Flathub removed aarch64 refs from the main summary (which hit the 10MB
limit). They are still accessible in the "sub-summary" which (lib)flatpak
knows how to use. Sadly eibflatpak.py bypasses libflatpak and attempts
to use the libostree API directly to pull Flatpak refs; libostree does
not know about sub-summaries so this fails.
https://phabricator.endlessm.com/T33827
=> Temporarily install no apps or runtimes from Flathub

config/defaults.ini
This contains a couple fixes for `importcontent` to ensure it reliably errors when it cannot download content files.
https://phabricator.endlessm.com/T33363
=> config: Update kolibri to 0.15.7

config/arch/arm64.ini, config/branch-arch/master-arm64.ini
In a80916f / 82122a2 "Temporarily install no apps or runtimes from
Flathub" I explicitly set [flatpak-remote-flathub-beta] apps and
runtimes to empty list on any arm64 build. However, flathub-beta is only
enabled on master builds. As a result, stable builds failed:
Traceback (most recent call last):
File "/tmp/image-build-WJso41ligR/eos-image-builder/hooks/content/50-flatpak", line 57, in <module>
manager = eibflatpak.FlatpakManager(installation, config=config,
File "/tmp/image-build-WJso41ligR/eos-image-builder/lib/eibflatpak.py", line 547, in __init__
self.remotes[name] = FlatpakRemote(self, name,
File "/tmp/image-build-WJso41ligR/eos-image-builder/lib/eibflatpak.py", line 197, in __init__
raise FlatpakError('No URL defined for remote', self.name)
eibflatpak.FlatpakError: No URL defined …
=> Only remove flathub-beta arm64 apps on master

config/arch/arm64.ini
The arm64 en images built failed, because failed to pull 'runtime/org.gnome.Platform.Locale/aarch64/3.28' from flathub. Besides, current com.endlessm.finance and com.endlessm.resume depend on runtime org.gnome.Platform//3.28. Here are two root causes:
* 'runtime/org.gnome.Platform.Locale/aarch64/3.28' does not exist on flathub anymore. This is tracked by "Move Resume & Finance/My Budget apps to modern tech stack, T33859".
* The ticket "T33827: Image builder can't install arm64 flatpaks from Flathub".
So, drop finance and resume from arm64 images temporarily.
https://phabricator.endlessm.com/T33876
=> config: arm64: Drop finance and resume temporarily

config/arch/arm64.ini
We have tried to drop finance and resume by the commit 392c15aa7fbb ("config: arm64: Drop finance and resume temporarily"). However, they are the apps of "eos-apps", not "flathub". This commit drops finance and resume from the correct source: eos-apps.
Fixes: 392c15aa7fbb config: arm64: Drop finance and resume temporarily
https://phabricator.endlessm.com/T33876
=> config: arm64: Drop finance and resume from eos-apps temporarily

.github/workflows/tests.yml, config/arch/arm64.ini, config/branch-arch/master-arm64.ini, hooks/content/50-flatpak, hooks/image/50-flatpak.chroot, lib/applist.py, lib/eibflatpak.py, tests/data/flatpak/app-1-locale/metadata, tests/data/flatpak/app-1/metadata, tests/data/flatpak/app-2-locale/metadata, tests/data/flatpak/app-2/metadata, tests/data/flatpak/app-extra-data/metadata, tests/data/flatpak/platform-1-locale/metadata, tests/data/flatpak/platform-1/metadata, tests/data/flatpak/platform-2-locale/metadata, tests/data/flatpak/platform-2/metadata, tests/eib/test_eibflatpak.py, tests/eib/test_eibostree.py, tests/util.py
I decided against doing a narrower backported and just took all the commits from #89 and #90. There were 2 issues:
* Some of the giant rewrite commit (0dae68c5f55adf120ae2c2b4ffdad742dd258b4b) didn't apply cleanly because on master I'd done some linting fixes that weren't backported. I left out the linting fixes since they're not necessary and the eos4.0 test suite isn't running `flake8`.
* The eibflatpak tests were exercising 9e0032985c69deb5f684c08fea26d9a4f73f22b1, but that wasn't backported. I just removed the parts that were trying to handle that.
https://phabricator.endlessm.com/T33827
=> Flatpak transaction backport

config/defaults.ini
EOS is going to switch from Rhythmbox to GNOME Music as default music player. So, drop Rhythmbox from the default config.
https://phabricator.endlessm.com/T34075
=> config: drop Rhythmbox from default config

hooks/image/50-xkb-layout.chroot
It accidentally overrode the entire file with a single EndSection instead of appending it. Fix it.
https://phabricator.endlessm.com/T34066
=> image: Fix 00-keyboard.conf file generation

hooks/image/60-kolibri-content
We see sporadic failures to import random pieces of content, due to the
Kolibri server returning something with the wrong checksum. (This is
believed to be the CDN serving an error, possibly a rate-limiting
error.) Typically, if we rerun the build, the error does not recur for
the same content file.
It is sad to fail a multi-hour, multi-hundred-gigabyte image build due
to a single broken content item. Add a retry loop around the import
function to try to recover.
https://phabricator.endlessm.com/T34149
=> kolibri: Retry if importing content fails

hooks/image/60-kolibri-content
We see sporadic failures to import random pieces of content, due to the Kolibri server returning something with the wrong checksum. (This is believed to be the CDN serving an error, possibly a rate-limiting error.) Typically, if we rerun the build, the error does not recur for the same content file.
It is sad to fail a multi-hour, multi-hundred-gigabyte image build due to a single broken content item. Retry `kolibri manage importcontent` once, after a short pause, in hope of recovering in this case.
https://phabricator.endlessm.com/T34149
(cherry picked from commit 6eb5b59f89612006d8634e1cb3687caca47cb0cb)
=> kolibri: Retry importcontent on error (eos4.0)

config/defaults.ini
The legacy runtimes have been copied out of the eos repo to a new eos-runtimes repo so that it can be treated as a pure flatpak repo. This starts a long process where eventually we can remove the legacy runtimes from the eos repo and treat it as a pure ostree repo.
https://phabricator.endlessm.com/T33445
=> config: Set eos-runtimes remote to use new repo URL

config/defaults.ini
The legacy runtimes have been copied out of the eos repo to a new eos-runtimes repo so that it can be treated as a pure flatpak repo. This starts a long process where eventually we can remove the legacy runtimes from the eos repo and treat it as a pure ostree repo.
https://phabricator.endlessm.com/T33445
(cherry picked from commit ee650095568fde01e689b9ca4cf0f8c54c25b562)
=> Backport "config: Set eos-runtimes remote to use new repo URL" to eos4.0

config/defaults.ini
The legacy runtimes have been copied out of the eos repo to a new eos-runtimes repo so that it can be treated as a pure flatpak repo. This starts a long process where eventually we can remove the legacy runtimes from the eos repo and treat it as a pure ostree repo.
https://phabricator.endlessm.com/T33445
(cherry picked from commit ee650095568fde01e689b9ca4cf0f8c54c25b562)
I did this as a cherry pick rather than fast-forwarding because master has 4e00e2b60221645e6c1e540c1311456e45b8db7f, which is not supposed to go on eos5.0 from what I can tell.
=> Backport "config: Set eos-runtimes remote to use new repo URL" to eos5.0

.github/workflows/tests.yml, config/defaults.ini
Although Chromium remains the default browser, Epiphany is required for Personal Web Application (PWA) support.
https://phabricator.endlessm.com/T34479
=> config: Add Epiphany to all images

config/defaults.ini
(cherry picked from commit 3b2cde7d7aabb2d71eb0d979a49773ba7df75306)
https://phabricator.endlessm.com/T33982
This is a backport of #53. I'm not backporting the other two bits (automatically installing this Flatpak on upgrade https://github.com/endlessm/eos-application-tools/pull/71 https://github.com/endlessm/eos-application-tools/pull/73; and removing it from the base OS https://github.com/endlessm/eos-meta/pull/723) because this is an LTS and I want to minimize changes to the OS. But the built-in version of Fonts on eos4.0 is just pretty broken, so in the case where people are building new eos4.0 images, they should get the Flatpak version.
=> config: Move gnome-font-viewer to flatpak

buildscript
Newer git prevents operations when the calling user is not the same as the user owning the repo. Currently the only git operation run is `git rev-parse HEAD` to record the builder commit in the manifest, but even that is enough to make git fail. Add the repo as a safe directory inside the build root since the builder is running as root and the repo may not be owned by root.
https://community.endlessos.com/t/custom-build-problem-with-5-0/19900
=> buildscript: Declare repo as a git safe directory

.editorconfig, .flake8, README.md, config/defaults.ini, hooks/content/50-kolibri-content
If a custom Kolibri content server is in use and credentials are
available, use the API to import the desired channels remotely. When the
time comes to populate the channels on the image, all the content will
be available on the server.
https://phabricator.endlessm.com/T33705
=> Kolibri remote import

stages/eib_ostree
Don't bother GPG verifying the summary if it's being fetched over HTTPS. This often fails when the summary is being updated concurrently since the received summary and summary signature can be mismatched. The built image is already configured to not verify the summary.
https://phabricator.endlessm.com/T32658
=> ostree: Don't verify summary on HTTPS

hooks/image/50-gnome-software-cache
2 changes are needed for the path:
* gnome-software now uses the non-legacy `/var/cache/swcatalog/xml` AppStream directory.
* gnome-software now includes a SHA1 hash of URL in the filename in case there are multiple external AppStream URLs with the same basename.
This also switches the XML to being downloaded rather than copied from the git repo. This validates the URL and ensures that the exact file is installed. This is what would happen if we later switch to using `gnome-software-cmd refresh`, anyways.
https://phabricator.endlessm.com/T34337
=> gnome-software-cache: Update eos-extra cached appstream path

config/defaults.ini, hooks/image/51-ek-content-list, hooks/image/52-ek-content-cache, hooks/image/53-ek-content-preload
We want to preload the whole Endless Key library in Endless OS images.
We also need to ensure the content is available in our Kolibri cache
server, if we are pulling the content from it.
https://github.com/endlessm/eos-image-builder/issues/117
=> Preload Endless Key content

hooks/image/51-ek-content-list
This will avoid trying to download and install the same channel more than once.
https://github.com/endlessm/eos-image-builder/issues/117
=> image: ek-content-list: Sort and dedup channel list

config/branch-personality/master-base.ini, config/branch/master.ini, config/defaults.ini, config/personality/base.ini
I think we want this installed by default for basically all images, although images that want preloaded content should also explicitly add it. For now I left org.learningequality.Kolibri preinstalled.
=> config: Install Endless Key by default

hooks/image/53-ek-content-preload, hooks/image/60-kolibri-content
Kolibri seems to have an unwelcome habit of persisting the values of environment variables in the options file when the homedir is being initialized. Among other things, that would cause our Kolibri content server to be used at runtime. As a bonus, all the subsequent management commands can be run with `--skip-update` since the database migration has already happened.
Helps: https://github.com/endlessm/endless-key-content-private/issues/103
=> hooks: Initialize Kolibri homedir before setting variables

.editorconfig, hooks/content/50-kolibri-content, hooks/image/52-ek-content-cache, hooks/image/53-ek-content-preload, hooks/image/60-kolibri-content
Kolibri defaults to only downloading content nodes that it believes the current instance can render. Both the image builder and the content server have Kolibri instances that don't necessarily have all available content renderers. To be safe they should download content nodes without regard for whether Kolibri thinks they're renderable. For the `importcontent` CLI, that's the `--include-unrenderable-content` option. For the task API, that's the `renderable_only` option.
Helps: https://github.com/endlessm/endless-key-content-private/issues/103
=> Fetch all Kolibri content nodes

hooks/image/70-flatpak-manifest
https://phabricator.endlessm.com/T35013
(I have another branch on the way to export a complete appstream catalogue for pre-installed apps but that one is rather slower to test.)
=> Add human-readable names & summaries to Flatpak manifest 

run-build
Since `mmdebstrap` is no longer being used, a populated apt cache directory can be mounted into the buildroot and the packages there will be reused instead of being downloaded again. This is essentially a revert of 1f7e15403a5e3525d81a69e8a33b4c64d8f5930c.
=> ImageBuildRoot: Bring back apt cache directory

.editorconfig, .flake8, config/defaults.ini, hooks/image/70-flatpak-appstream-catalog, hooks/publish/45-publish-s3
Although we have added the name and summary for each app to the JSON manifest, there is no substitute for having all the data. XML compresses very well!
It is better to capture this at build time rather than fetching it on the fly later because apps can change or disappear, but we would like to be able to describe exactly what is in any given image.
https://phabricator.endlessm.com/T35013
=> Export appstream catalogue for preinstalled Flatpak apps

config/platform/nexthw.ini, tests/test_image_builder.py
The nexthw build is dropped since EOS 5.1.
https://phabricator.endlessm.com/T35027
=> Drop nexthw platform config

config/personality/es.ini
This game making application is currently only useful in Spanish, so we will add it to the "es" personality.
https://phabricator.endlessm.com/T34960
=> config: Add ar.com.pilas_engine.App to es images

config/defaults.ini
We are no longer maintaining Hack. The apps will remain available on Flathub (unless/until they are EOLed) and installed on existing systems.
https://phabricator.endlessm.com/T35054
=> Stop installing Hack apps by default

lib/eibflatpak.py
Previously, if a listed Flatpak app or runtime is not present in that
remote, remote.match() would return None, but the calling code would
assume it is not None. This leads to a failure like this:
+ 20:16:29 INFO eibflatpak: Looking for app ref "com.orama_interactive.Pixelorama" match in flathub
+ 20:16:29 INFO eibflatpak: Removing repo option core.xa.languages
+ 20:16:29 INFO eibflatpak: Removing repo option core.xa.extra-languages
+ 20:16:29 INFO eibflatpak: Removing repo option core.xa.masked
Traceback (most recent call last):
File "/tmp/image-build-IZAJlTeyep/eos-image-builder/hooks/content/50-flatpak", line 61, in <module>
manager.pull()
File "/tmp/image-build-IZAJlTeyep/eos-image-builder/lib/eibflatpak.py", line 837, in pull
txn = self._new_transaction()
File …
=> Handle missing Flatpaks gracefully

lib/eibkolibri.py
This isn't a time critical operation, so sleep a bit between requests to check the job status so the server isn't being hammered. While here, include the netrc path when logging about missing credentials.
This is a follow up to incorporate some feedback in #137.
https://phabricator.endlessm.com/T34697
=> eibkolibri: Back off a bit when checking job status

config/defaults.ini
If the build needs to install a Python package from PyPI (like hooks/image/60-kolibri-content), it's possible that it will need to be built natively from source if there are no binary wheels available for the current Python version. That fails if the Python development environment isn't available.
https://phabricator.endlessm.com/T35125
=> config: Install python3-dev package in buildroot

.github/workflows/tests.yml, README.md, lib/eibkolibri.py, requirements-test.txt, tests/eib/test_eibkolibri.py
Eventually we're going to want to update our content server to Kolibri 0.16 since it will soon be the new stable version and because it has lots of bug fixes in content handling. Unfortunately, the tasks API that's used when seeding content from the image builder changed.
Initially I changed it directly to just use the 0.16 API, but then I decided I didn't want to have a flag day. This makes the image builder support both series. In addition to some manual testing, I added some unit tests to prove it out to myself. That will let us land the necessary changes in the image builder and later update the server when we feel it's appropriate (like when 0.16.0 is finally released).
This is branched from eos5.1 to ease later backporting since we'll want to have this on all active branches. …
=> Support Kolibri 0.16 tasks API

lib/eibkolibri.py
If new nodes are added in a new channel version, the channel needs to be updated or they will be skipped if they're below an already existing node. However, if there are missing nodes from a previously failed import, then a regular import is needed. Therefore, follow a channel update with a channel import.
The update is run first because the algorithm for calculating newly needed nodes depends on comparing the old and new versions of the channel metadata. One a regular import is done, the old version of the channel metadata is replaced and the calculation can't be made anymore.
https://phabricator.endlessm.com/T34697
=> eibkolibri: Follow channel update with channel import

run-build
Sadly https://github.com/endlessm/eos-ostree-builder/pull/189 broke the image builder, because we create the buildroot by deploying an ostree, and the various things that set up `/var` on a fresh system are not all done here.
https://phabricator.endlessm.com/T4482
=> Recreate /var

config/defaults.ini, config/personality/en.ini, hooks/image/53-ek-content-preload
The previous behaviour, of importing all content from all channels in the collections, is preserved by setting include_full_channels to true.
https://phabricator.endlessm.com/T35103
=> endlesskey: Import only specified content in collections

run-build
When running the image builder on Endless OS, there is a high chance that the host system will be running a similar, if not identical, OSTree commit to the one being built into the image. In my case, I run master and update essentially every morning, so running the image builder with its default arguments will use the same OSTree as is booted.
`ostree pull` supports a `--localcache-repo PATH` argument:
> Like git's clone --reference. Reuse the provided OSTree repo as a
> local object cache when doing HTTP fetches.
In this patch, we bind-mount the host's /ostree/repo into the buildroot, if it exists. The bind-mount is made read-only to reduce the risk that a bug in the image builder will mess up the host system.
This is obviously a hack but I thought I'd give it a try and it seems to make …
=> Use host ostree as localcache repo

config/defaults.ini
This has been updated in the org.learningequality.Kolibri flatpak. Most importantly, its Pillow dependency has been updated to a version that has binary wheels for Python 3.11.
https://phabricator.endlessm.com/T35125
=> kolibri: Update kolibri-app-desktop-xdg-plugin to 1.2.0

config/personality/en.ini
This reverts commit 2233b93d25fe40893b50a25e14d9c04dcc8d1fda.
Instead, the Spanish content we want to be available is being added in endlessm/endless-key-collections#39.
https://phabricator.endlessm.com/T35170
=> Revert "config: Add spanish-extras collection to the es personality"

config/defaults.ini
Cheese was moved from the OS to a Flatpak in eos4.0. There has been a checkpoint between eos4.0 and eos5.0+, so we can now remove the flatpak-autoinstall.d rule that requires it to be installed. It follows that we can relegate it to "default" status, which in particular means that base images need no longer include it.
Depends on:
https://phabricator.endlessm.com/T35175
=> Remove Cheese from mandatory apps

config/defaults.ini
In eos4.0 (and earlier), gnome-logs was baked into the OSTree. It is in apps_add_mandatory because we used flatpak-autoinstall.d to cause the Flatpak version to be installed when upgrading from eos4.0 to eos5.[01] so that the app does not disappear with the upgrade.
However this is really quite a niche app, so we will just stop doing that. Our metrics show that this app is very seldom used. People who need to read the journal, and prefer this app to journalctl, can install it from the App Center.
Depends on:
https://phabricator.endlessm.com/T35176
=> Stop preinstalling GNOME Logs

helpers/create-iso
In effect, this reverts 4a167ae3bd3dd67785d21cc3a1cbacc4fefcee36 and
a2f1eb46ae0008283b926f56cab8d7f6a4ec02e8.
In the past, the Endless Installer for Windows was under active
development, with corresponding changes in the OS. To be able to e.g.
test the installer from within an ISO built by our infrastructure before
releasing the installer changes to the public, we had to fetch the
installer from a branched URL.
Now the installer is essentially dead, this just adds extra steps to our
release process for no benefit. Fetch from an unbranched URL.
I stand by the TODO I wrote in 977b96d8b0ae44c431b8596ddf4871e5377f311e
though it seems vanishingly unlikely we will ever do that.
https://phabricator.endlessm.com/T35105
=> create-iso: Use non-branched endless-installer.exe

config/arch/arm64.ini
This reverts commit 4b2d57a37d14ef927ccda9e1c2179231b02f0430.
https://github.com/flathub/io.gdevelop.ide/pull/30 was accepted: GDevelop should be available for arm64 in the coming hours!
=> Revert "arm64: Exclude GDevelop"

config/defaults.ini
I learned today that, in addition to the
runtime/org.freedesktop.Platform.ffmpeg-full/$ARCH/23.08 extension that exists on
all architectures, on x86_64 there is also
runtime/org.freedesktop.Platform.ffmpeg_full.i386/x86_64/23.08 to
support 32-bit binaries in an otherwise 64-bit environment. This runtime
was not being explicitly excluded from our images.
I checked the image server database with the following query:
select
build_id
from
builds_manifest
where
(data -> 'flatpak' -> 'runtimes') ?| array[
'org.freedesktop.Platform.ffmpeg_full.i386/x86_64/20.08',
'org.freedesktop.Platform.ffmpeg_full.i386/x86_64/21.08',
'org.freedesktop.Platform.ffmpeg_full.i386/x86_64/22.08',
'org.freedesktop.Platform.ffmpeg_full.i386/x86_64/23.08'
]
limit 1;
(`object ?| keys` is true if the JSON value `object` …
=> Exclude org.freedesktop.Platform.ffmpeg_full.i386 extension

config/defaults.ini
This partially reverts afc6ff82c814903eaa8ac22e524e7ea334b16146
(“config: Include H.264 and MPEG4 by default”).
It is not necessary to explicitly install these:
- If org.chromium.Chromium is to be installed (which in practice it
always is) then since its extension org.chromium.Chromium.Codecs has
autodownload enabled (or strictly speaking has no-autodownload
disabled) and is not masked by the 'exclude' list in the image builder
config, it will be automatically installed by Flatpak while installing
Chromium.
- Similarly, since all modern runtimes have an extension point for
org.freedesktop.Platform.openh264 with autodownload enabled, since it
is not excluded it will be installed automatically by Flatpak.
Listing them explicitly is actually not harmless at present because openh264 is …
=> defaults: Don't explicitly add openh264 or Chromium.Codecs

config/defaults.ini, helpers/packages-manifest, hooks/image/70-packages-manifest, stages/eib_image
The ostree commits now ship with an empty `/var`, which means that `/var/lib/dpkg/status` doesn't exist. Use `/usr/share/dpkg/database` instead, which is what `/var/lib/dpkg` is a symlink to at runtime.
https://phabricator.endlessm.com/T35244
=> Fix dpkg queries

config/defaults.ini
Image Viewer (codenamed Loupe) is a the new core image viewer app. Pairs with https://github.com/endlessm/eos-meta/pull/766.
https://phabricator.endlessm.com/T34908
=> defaults: Add Image Viewer

config/defaults.ini
https://phabricator.endlessm.com/T32696
=> defaults: add Decibels & Music

config/defaults.ini
Files (Nautilus) has built-in archive handling, now, so we don't need to include File Roller.
https://phabricator.endlessm.com/T35285
=> defaults: Remove File Roller

config/defaults.ini
`com.vixalien.decibels` is now marked EOL since Flathub has added `org.gnome.Decibels`.
https://phabricator.endlessm.com/T32696
=> config: Update Decibels app ID

config/arch/amd64.ini, config/defaults.ini, config/product-personality/eos-base.ini, stages/eib_image
It's a nice format for loading in GNOME Boxes or any VM tool that uses QEMU. In particular, it's the native format used by GNOME Boxes.
https://phabricator.endlessm.com/T35332
=> Support QEMU qcow2 image format

config/defaults.ini, hooks/image/53-ek-content-preload, hooks/image/63-kolibri-chown.chroot
tmpfiles.d configuration is provided for both that changes ownership to kolibri:kolibri for both at runtime. However, if there's an overlayfs on /var like there is when booting an ISO, all the files are copied to the upper tmpfs. That's likely to OOM the system when either is filled with preloaded data.
One possibility is to run the tmpfiles.d configuration here. For simplicity, we just run `chown` here. For Kolibri, a separate hook is added since the content generation is split across 3 hooks.
https://phabricator.endlessm.com/T35498
I haven't run this at all, but I believe it's correct.
=> image: Chown Kolibri and Endless Key data

lib/eib.py, tests/eib/test_image_config_parser.py
The order of configuration values may be significant, so the parser should not sort them. To do that, use a single counter for add and del variants and emit the values that have positive counts without sorting. This relies on the Python dict stable order, which has been the case since Python 3.6.
I've done no real world testing of this. It should also be stated that the order you get is "first merged section wins", so it's not really reliable. For example:
```
[section]
option_add_product = foo
option_add_local_product = bar
```
You'd get `foo\nbar` even though you might really prefer `bar\nfoo` from your local setting. With explicit sorting you'd always get the same values regardless of what order the unmerged options came in.
=> ImageConfigParser: Don't sort merged values

config/defaults.ini, config/personality/en.ini, config/personality/es.ini, config/personality/fr.ini, lib/eib.py, run-build, tests/test_image_builder.py
It is often the case that we want to build an image which just applies a
few minor changes to an existing personality.  For instance, the apps we
want for most Spanish images are the same, but we have a few
country-specific applications, and we often wish to build a sub-variant
for a partner or region of a particular country.
Currently we need to copy the full list of apps & settings from our
es.ini personality config into (for instance) es_MX.ini; and then again
from es_MX.ini into (e.g.) es_MX_aguascalientes.ini to add some
region-specific apps or resources
Implement a form of inheritance where (e.g.) building the es_MX
personality reads es.ini and es_MX.ini, in that order; and (e.g.)
building the es_MX_aguascalientes personality reads es.ini, es_MX.ini
and es_MX_aguascalientes.ini, …
=> Add config inheritance for personality field

README.md, config/schema.ini, run-build, tests/test_image_builder.py
Previously, if a filename referred to in the configuration does not exist, that would only be discovered when the hook which uses that key runs, which may be minutes or hours into the build.
Add a way to specify in the schema that certain keys must be set to a single path to an extant file, or a list of paths to extant files.
Add `key_type = path(s)` annotations to the schema for all (I think) of the file-like `key`s used by hooks in this repo.
https://phabricator.endlessm.com/T35517
=> Add validation for paths in config

hooks/image/54-ek-launchers
Is this the right idea? It sort of feels dirty to include a whole shell script here. And do I need to make it executable?
https://phabricator.endlessm.com/T35614
=> Hooks: Add hook to expose Endless Key launchers in app grid

hooks/image/53-ek-content-preload
EIB_ENDLESSKEY_COLLECTIONS is a whitespace (typically space or newline)-separated list of collection names. These are matched against collection filenames to determine what to fetch.
We have collection files named `extras-preload-0001.json` and `spanish-extras-preload-0001.json`. The intention is that if `[endlesskey] collections` contains `spanish-extras-preload` but not `extras-preload`, only the latter will be imported, not the former.
However, the logic that matched filenames against the configured array did not consider the case when one collection name is a substring of another. It would incorrectly match `extras-preload-0001.json` against `spanish-extras-preload` because the latter contains `extras-preload` as a substring.
Replace runs of whitespace in EIB_ENDLESSKEY_COLLECTIONS …
=> Match selected Endless Key content collections correctly

config/defaults.ini, hooks/image/53-ek-content-preload
Endless Key was designed to be used via a single entrypoint, rather than per-channel launchers as we have for Kolibri on Endless OS. However, a partner have specifically requested per-channel launchers coupled with the Endless Key interface & content. To support them, Endless Key bundles the same xdg plugin for Kolibri as for the kolibri-gnome app, which generates .desktop files etc. into `/var/lib/endless-key/data/content/xdg/share/`. Then in this partner's OS image, we drop a file into /etc/systemd/user-environment-generators to add this directory to XDG_DATA_DIRS, just like the file we ship in /usr/systemd/user-environment-generators for Kolibri.
However, previously that path was not pre-populated in the image builder for Endless Key content that is preloaded into the image. This is …
=> Populate .desktop files for Endless Key channels

config/defaults.ini, hooks/image/50-eos-dir-mode-700
The purpose of this hook was to write a stamp file to prevent a migration task being run on new systems.
The migration task in question was removed in Endless OS 3.5 back in 2018.
https://github.com/endlessm/eos-boot-helper/commit/ae137ab6dd2203422ccecc62ca58c1369f602079 https://phabricator.endlessm.com/T22548
=> Remove eos-dir-mode-700 hook

.github/workflows/tests.yml
GitHub announced:
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-15. [1]
So, bump the runner to ubuntu-latest directly.
[1]: https://github.com/actions/runner-images/issues/11101
=> tests: Replace GitHub Actions ubuntu-20.04 runner with 24.04

config/personality/es.ini
These content flatpak apps and Kolibri channels are added by PR: "config: ES: Add more apps into generic EOS ES images" [1]. The plenty of content is good, but it also makes image become heavy to 57.1 GB (compressed). Downloading takes much more time. Besides, we also want to differentiate our impact images from common images. Although, the users still can download the flatpak apps and Kolibri channels by themselves actually.
So, drop the modification from the PR "config: ES: Add more apps into generic EOS ES images" for the migration.
This reverts commits d2a56d44cf11 ("config: ES: Add more apps into generic EOS ES images") and e345f8653e48 ("config: ES: Add Kolibri channels into ES").
[1]: https://github.com/endlessm/eos-image-builder/pull/174
https://phabricator.endlessm.com/T35862
=> config: ES: Migrate some flatpak apps and Kolibri channels to eosimpact-es.ini

helpers/eib-chroot
Changing root with nested chroot command makes flatpak fail to convert FlatpakExports to bwrap arguments in the hook script 50-flatpak.chroot:
```
(process:5470): flatpak-DEBUG: 12:04:39.307: Converting FlatpakExports to bwrap arguments...
(process:5470): flatpak-DEBUG: 12:04:39.307: D-Bus proxy not needed
flatpak-INFO: 12:04:39.307: Running /app/bin/apply_extra
bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
```
So, use bwrap to change root into the sandbox to avoid permission issue.
Part-of: https://github.com/endlessm/eos-build-meta/issues/102
=> eib-chroot: Use bwrap for chroot

config/defaults.ini, hooks/image/10-systemd-tmpfiles.chroot
This is to fix an issue during the 50-flatpak image hook, which would fail at the appstream update with this:
gi.repository.GLib.GError: g-io-error-quark: While pulling appstream2/x86_64 from remote flathub: open(O_TMPFILE): No such file or directory (1)
The root cause being a lack of `/var/tmp` in the ostree checkout.
It's surprising that things worked as well as they did until now, and perhaps is due to the ostree containing more things in `/var/` than it should.
=> Run systemd-tmpfiles in the ostree checkout

helpers/install-awscli
By default `unzip` lists every file it unpacks, which produces over 8000 lines of log output.  Add `-q` to avoid that.
=> helpers/install-awscli: Avoid 8000 lines of messages from `unzip`

config/defaults.ini
This is freedesktop-sdk 25.08's successor to ffmpeg-full, which also includes encumbered HEIC support for libheif (which is now part of the runtime).
=> Exclude codecs-extra extension
